# Generated by Django 5.1.6 on 2025-02-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_uploadedvideo_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedvideo',
            name='clip_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
